[versions]
kotlin = "2.2.20"
brigadier = "1.0.18"
korigadier = "1.0.2"
junit = "5.10.2"

[libraries]
brigadier = { module = "com.mojang:brigadier", version.ref = "brigadier" }
korigadier = { module = "io.github.oni0nfr1:korigadier", version.ref = "korigadier" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version = "9.3.0" }
