[versions]
kotlin = "2.2.20"
brigadier = "1.0.18"
paper = "1.21.8-R0.1-SNAPSHOT"
junit = "5.10.2"

[libraries]
brigadier = { module = "com.mojang:brigadier", version.ref = "brigadier" }
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
